/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2024-02-26 09:37:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CustomerRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("   \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Register</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\"></link>\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- Font Awesome CSS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/register.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:#ffc3a149;\">\r\n");
      out.write("	<div\r\n");
      out.write("		class=\"container position-absolute top-50 start-50 translate-middle p-2 mb-5 text-dark shadow-lg rounded\">\r\n");
      out.write("\r\n");
      out.write("		<p class=\"fw-bolder fs-2 text-center\">Register</p>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("			<form class=\"row g-3\" action=\"registerCustomer\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<label for=\"fname\" class=\"form-label\">First name</label> <input\r\n");
      out.write("						type=\"text\" class=\"form-control def\" id=\"fname\" name=\"custName\"\r\n");
      out.write("						placeholder=\"Enter your first name\" required>\r\n");
      out.write("					<div class=\"valid-feedback\">Looks good!</div>\r\n");
      out.write("					<div class=\"invalid-feedback\">Enter a valid name!</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<label for=\"lname\" class=\"form-label\">Last name</label> <input\r\n");
      out.write("						type=\"text\" class=\"form-control def\" id=\"lname\"\r\n");
      out.write("						placeholder=\"Optional...\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<label for=\"uemail\" class=\"form-label\">Email</label>\r\n");
      out.write("					<div class=\"input-group has-validation\">\r\n");
      out.write("						<input type=\"email\" class=\"form-control def\" id=\"uemail\"\r\n");
      out.write("							name=\"custEmail\" placeholder=\"Enter your email id\"\r\n");
      out.write("							style=\"border-radius: 20px;\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("						<div class=\"invalid-feedback\">Please choose a username.</div>\r\n");
      out.write("						<div class=\"valid-feedback\">Looks Good!</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<label for=\"cnumber\" class=\"form-label\">Contact Number</label> <input\r\n");
      out.write("						type=\"text\" class=\"form-control def\" id=\"cnumber\"\r\n");
      out.write("						name=\"custContact\" placeholder=\"Enter your contact number\"\r\n");
      out.write("						required>\r\n");
      out.write("					<div class=\"valid-feedback\">Looks good!</div>\r\n");
      out.write("					<div class=\"invalid-feedback\">Enter a valid mobile number!</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<label for=\"upass\" class=\"form-label\">Password</label> <input\r\n");
      out.write("						type=\"password\" class=\"form-control def\" id=\"upass\"\r\n");
      out.write("						name=\"custPass\" placeholder=\"Choose a strong password\" required>\r\n");
      out.write("					<div class=\"valid-feedback\">Looks good!</div>\r\n");
      out.write("					<div class=\"invalid-feedback\">Weak Password!</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<label for=\"upassc\" class=\"form-label\">Confirm Password</label> <input\r\n");
      out.write("						type=\"password\" class=\"form-control def\" id=\"upassc\"\r\n");
      out.write("						placeholder=\"Confirm your password\" required>\r\n");
      out.write("					<div class=\"valid-feedback\">Password matched successfully!</div>\r\n");
      out.write("					<div class=\"invalid-feedback\">Password not match!</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<label for=\"city\" class=\"form-label\">City</label> <input\r\n");
      out.write("						type=\"text\" class=\"form-control def\" id=\"city\" name=\"custCity\"\r\n");
      out.write("						placeholder=\"Enter your city\" required>\r\n");
      out.write("					<div class=\"invalid-feedback\">Please provide a valid city.</div>\r\n");
      out.write("					<div class=\"valid-feedback\">Looks good!</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<label for=\"state\" class=\"form-label\">State</label> <select\r\n");
      out.write("						class=\"form-select def\" id=\"state\" name=\"custState\"\r\n");
      out.write("						style=\"border-radius: 10px;\" required>\r\n");
      out.write("						<option selected disabled value=\"\">Choose...</option>\r\n");
      out.write("						<option value=\"Maharashtra\">Maharashtra</option>\r\n");
      out.write("						<option value=\"Gujarat\">Gujarat</option>\r\n");
      out.write("						<option value=\"Madhya Pradesh\">Madhya Pradesh</option>\r\n");
      out.write("						<option value=\"Rajasthan\">Rajasthan</option>\r\n");
      out.write("						<option value=\"Telangana\">Telangana</option>\r\n");
      out.write("						<option value=\"Andhra Pradesh\">Andhra Pradesh</option>\r\n");
      out.write("						<option value=\"Tamil Nadu\">Tamil Nadu</option>\r\n");
      out.write("						<option value=\"Karnataka\">Karnataka</option>\r\n");
      out.write("						<option value=\"Kerela\">Kerela</option>\r\n");
      out.write("					</select>\r\n");
      out.write("					<div class=\"invalid-feedback\">Please select a valid state.</div>\r\n");
      out.write("					<div class=\"valid-feedback\">Looks good!</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<label for=\"pincode\" class=\"form-label\">Pin Code</label> <input\r\n");
      out.write("						type=\"text\" class=\"form-control def\" id=\"pincode\" name=\"custPin\"\r\n");
      out.write("						placeholder=\"Enter your zip code\" required>\r\n");
      out.write("					<div class=\"invalid-feedback\">Please provide a valid pin\r\n");
      out.write("						code.</div>\r\n");
      out.write("					<div class=\"valid-feedback\">Looks good!</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<div class=\"form-check\">\r\n");
      out.write("						<input class=\"form-check-input def\" type=\"checkbox\" value=\"\"\r\n");
      out.write("							id=\"agree\" required> <label class=\"form-check-label\"\r\n");
      out.write("							for=\"invalidCheck3\"> Agree to terms and conditions </label>\r\n");
      out.write("						<div class=\"invalid-feedback\">You must agree before\r\n");
      out.write("							submitting.</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12 mt-4\">\r\n");
      out.write("					<input type=\"submit\" class=\"btn btn-danger disabled\" id=\"register\"\r\n");
      out.write("						value=\"Register\">\r\n");
      out.write("					</button>\r\n");
      out.write("					<input type=\"reset\" class=\"btn btn-danger ms-3 disabled\"\r\n");
      out.write("						id=\"cancel\" value=\"Cancel\">\r\n");
      out.write("					</button>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<p class=\"text-center text-dark\">\r\n");
      out.write("			Already Registered? Want to <a href=\"loginPageRequest\"\r\n");
      out.write("				class=\"text-decoration-none\">Sign in </a>\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"position-fixed bottom-0 end-0 p-3\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"#\"> <img\r\n");
      out.write("				src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assests/icons/LOGO.png\"\r\n");
      out.write("				alt=\"Your Logo\" style=\"height: 80px; width: 200px\" class=\"rounded\">\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!-- Custom JS -->\r\n");
      out.write("	<script type=\"text/javascript\"\r\n");
      out.write("		src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/customer-register.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
